service:
  name: ms-users
  image: quay.io/dborrego/logging-ms-users
  version: 0.1

deployment:
  replicas: 3
  port: 8080
  health:
    liveness: /q/health/live
    readiness: /q/health/ready
  resources: 
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi

mariadb:
  database: users
  user: users

config:
  env: